#ifndef PCH_HPP_GUARD
#define PCH_HPP_GUARD

#include NAMES_INCLUDE

#include STL_INCLUDE_PATH
#include SETTINGS_INCLUDE_PATH		
#include TYPES_INCLUDE_PATH			
#include WINDOWS_INCLUDE_PATH		
#include TEST_UTILITIES_INCLUDE_PATH
#include UTILITIES_INCLUDE_PATH	
#include CODES_INCLUDE_PATH		
#include ERROR_INCLUDE_PATH	
#include FILELOGGER_INCLUDE_PATH		
#include LOGS_INCLUDE_PATH			
#include WINDOWLOGGER_INCLUDE_PATH	
#include BASIC_INCLUDE_PATH	
#include EXCEPT_INCLUDE_PATH
#include RANDOM_INCLUDE_PATH
#include UI_INCLUDE_PATH
#include MAIN_INCLUDE_PATH

#endif

